# image path
img_path: 'images/night_sky1.jpg'
out_dir: 'output'

# stars.py
ScaleAbs:
  alpha: 1
  beta: 3
GaussianBlur:
  size: 9
  sigma: 0
  ## for bright moon
  # sigma: 1000
HoughCircles:
  minDist: 20  # the minimum distance between the centers of the detected circles
  param1: 10  # the max threshold of the edge detector
  param2: 5  # the threshold of the circle center
  minRadius: 0
  maxRadius: 5
  ## for bright moon
  # param1: 30
  # param2: 10
  # minRadius: 40
  # maxRadius: 50

# sky_top.py
expected_center: [2500, -1200]
expected_radius: 400
ignore_angle_scope: [45, 180]
HoughLinesP:
  threshold: 40
  minLineLength: 100
  maxLineGap: 30

# calculate.py
is_fix_refraction_error: False  # whether to fix the air refraction error
sky_top_img_pst: [2464.72242052, -1206.3301124]
stars_img_pst:
  - [1410.5, 1398.5]  # 南河三
  - [2221.5, 453.5]  # 井宿三
  - [2585.5, 2604.5]  # 天狼
  - [3034.5, 885.5]  # 参宿四
  - [3967.5, 1766.5]  # 参宿七
  - [3567.5, 819.5]  # 参宿五
  - [3395.5, 1965.5]  # 参宿六
  - [3405.5, 1439.5]  # 参宿一
  - [3476.5, 1367.5]  # 参宿二
  - [3536.5, 1295.5]  # 参宿三
stars_sky_pst:  # Star coordinates in the angle system of coordinate at 0°N, 0°E position
  - [[15,9,2.01], [5,9,42.8]]  # 南河三
  - [[16,10,29.79], [16,22,41.6]]  # 井宿三
  - [[16,3,23.47], [-16,-45,-7.7]]   # 天狼
  - [[16,53,7.58], [7,24,38.2]]  # 参宿四
  - [[17,33,54.58], [-8,-10,-33.5]]  # 参宿七
  - [[17,23,10.89], [6,22,13.7]]  # 参宿五
  - [[17,0,42.23], [-9,-39,-47.7]]  # 参宿六
  - [[17,7,37.74], [-1,-55,-53.4]]  # 参宿一
  - [[17,12,10.07], [-1,-11,-17.4]]  # 参宿二
  - [[17,16,22.00], [0,-16,-58]]  # 参宿三